title: Pāṇini Protocol
remote_theme: just_the_docs/just_the_docs
runs-on: self-hosted
# Optional: auto sidebar
just_the_docs:
  aux_links:
    "GitHub Repo": https://github.com/ugrashravas/paniniprotocol
  logo: "img/ugrashravas.jpg"